package events

import (
	"github.com/filecoin-project/mir/pkg/pb/availabilitypb"
	"github.com/filecoin-project/mir/pkg/pb/eventpb"
	"github.com/filecoin-project/mir/pkg/pb/requestpb"
	requestpbtypes "github.com/filecoin-project/mir/pkg/pb/requestpb/types"
	t "github.com/filecoin-project/mir/pkg/types"
)

// These 2 functions convert between the two types of request events: (i) the newer type used by the newest DSL codegen featured
// contained in requestpb/types and used by the availability module, and (ii) the old type
// generated by the lecagy make generate contained in requestpb and used by the modules written prior to the newest codegen.
// TODO remove once all modules use newest DSL codegen

func RequestConvertToLegacyDsl(txs []*requestpbtypes.Request) []*requestpb.Request {
	_txs := make([]*requestpb.Request, len(txs))
	for i, tx := range txs {
		_txs[i] = tx.Pb()
	}
	return _txs
}

func RequestConvertFromLegacyDsl(txs []*requestpb.Request) []*requestpbtypes.Request {
	_txs := make([]*requestpbtypes.Request, len(txs))
	for i, tx := range txs {
		_txs[i] = requestpbtypes.RequestFromPb(tx)
	}
	return _txs
}

// ComputeCert is also needed for iss to call the ComputeCert event, because ISS does not use the DSL module.
func ComputeCert(destModule t.ModuleID) *eventpb.Event {
	return &eventpb.Event{
		DestModule: destModule.Pb(),
		Type: &eventpb.Event_Availability{
			Availability: &availabilitypb.Event{
				Type: &availabilitypb.Event_ComputeCert{
					ComputeCert: &availabilitypb.ComputeCert{},
				},
			},
		},
	}
}
