// Code generated by Mir codegen. DO NOT EDIT.

package communicationpbmsgs

import (
	blockchainpb "github.com/filecoin-project/mir/pkg/pb/blockchainpb"
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/communicationpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/messagepb/types"
	types "github.com/filecoin-project/mir/pkg/types"
)

func NewBlockMessage(destModule types.ModuleID, block *blockchainpb.Block) *types1.Message {
	return &types1.Message{
		DestModule: destModule,
		Type: &types1.Message_Communicationpb{
			Communicationpb: &types2.Message{
				Type: &types2.Message_NewBlock{
					NewBlock: &types2.NewBlockMessage{
						Block: block,
					},
				},
			},
		},
	}
}
