linters:
  enable:
    - gofmt
    - govet
    - goimports
    - misspell
    - goconst
    - gocyclo
    - errcheck
    - gosec
    - unconvert
    - staticcheck
    - varcheck
    - structcheck
    - deadcode
    - exportloopref
    - revive
    - dupl

run:
  timeout: 2m

issues:
  exclude-rules:
    - path: .*\.pb\.mir\.go
      linters: [revive, golint]
