linters:
  enable:
    - gofmt
    - govet
    - goimports
    - misspell
    - goconst
    - gocyclo
    - errcheck
    - gosec
    - unconvert
    - staticcheck
    - varcheck
    - structcheck
    - deadcode
    - exportloopref
    - revive
    - dupl
    - gosimple
    - gocognit
    - unused
    - stylecheck
    - ineffassign
    - unconvert
    - varcheck
    - errorlint

linters-settings:
  goimports:
    local-prefixes: github.com/filecoin-project/mir
  gocognit:
    min-complexity: 50

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: .*\.pb\.mir\.go
      linters: [revive, stylecheck, goimports]
