linters:
  enable:
    - gocyclo
    - revive
    - dupl
    - unconvert
    - goconst
    - gosec
    - gofmt
    - misspell

issues:
  exclude-rules:
    - path: .*\.pb\.mir\.go
      linters: [revive]
