// Code generated by Mir codegen. DO NOT EDIT.

package pprepvalidatorpb

import (
	contextstorepb "github.com/filecoin-project/mir/pkg/pb/contextstorepb"
	dslpb "github.com/filecoin-project/mir/pkg/pb/dslpb"
)

type Event_Type = isEvent_Type

type Event_TypeWrapper[T any] interface {
	Event_Type
	Unwrap() *T
}

func (w *Event_ValidatePreprepare) Unwrap() *ValidatePreprepare {
	return w.ValidatePreprepare
}

func (w *Event_PreprepareValidated) Unwrap() *PreprepareValidated {
	return w.PreprepareValidated
}

type ValidatePreprepareOrigin_Type = isValidatePreprepareOrigin_Type

type ValidatePreprepareOrigin_TypeWrapper[T any] interface {
	ValidatePreprepareOrigin_Type
	Unwrap() *T
}

func (w *ValidatePreprepareOrigin_ContextStore) Unwrap() *contextstorepb.Origin {
	return w.ContextStore
}

func (w *ValidatePreprepareOrigin_Dsl) Unwrap() *dslpb.Origin {
	return w.Dsl
}
