// Code generated by Mir codegen. DO NOT EDIT.

package testerpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	events "github.com/filecoin-project/mir/pkg/pb/testerpb/events"
	types "github.com/filecoin-project/mir/pkg/types"
)

// Module-specific dsl functions for emitting events.

func Tester(m dsl.Module, destModule types.ModuleID) {
	dsl.EmitEvent(m, events.Tester(destModule))
}
