// Code generated by Mir codegen. DO NOT EDIT.

package applicationpbtypes

import (
	mirreflect "github.com/filecoin-project/mir/codegen/mirreflect"
	applicationpb "github.com/filecoin-project/mir/pkg/pb/blockchainpb/applicationpb"
	payloadpb "github.com/filecoin-project/mir/pkg/pb/blockchainpb/payloadpb"
	reflectutil "github.com/filecoin-project/mir/pkg/util/reflectutil"
)

type Event struct {
	Type Event_Type
}

type Event_Type interface {
	mirreflect.GeneratedType
	isEvent_Type()
	Pb() applicationpb.Event_Type
}

type Event_TypeWrapper[T any] interface {
	Event_Type
	Unwrap() *T
}

func Event_TypeFromPb(pb applicationpb.Event_Type) Event_Type {
	if pb == nil {
		return nil
	}
	switch pb := pb.(type) {
	case *applicationpb.Event_NewHead:
		return &Event_NewHead{NewHead: NewHeadFromPb(pb.NewHead)}
	case *applicationpb.Event_PayloadRequest:
		return &Event_PayloadRequest{PayloadRequest: PayloadRequestFromPb(pb.PayloadRequest)}
	case *applicationpb.Event_PayloadResponse:
		return &Event_PayloadResponse{PayloadResponse: PayloadResponseFromPb(pb.PayloadResponse)}
	}
	return nil
}

type Event_NewHead struct {
	NewHead *NewHead
}

func (*Event_NewHead) isEvent_Type() {}

func (w *Event_NewHead) Unwrap() *NewHead {
	return w.NewHead
}

func (w *Event_NewHead) Pb() applicationpb.Event_Type {
	if w == nil {
		return nil
	}
	if w.NewHead == nil {
		return &applicationpb.Event_NewHead{}
	}
	return &applicationpb.Event_NewHead{NewHead: (w.NewHead).Pb()}
}

func (*Event_NewHead) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*applicationpb.Event_NewHead]()}
}

type Event_PayloadRequest struct {
	PayloadRequest *PayloadRequest
}

func (*Event_PayloadRequest) isEvent_Type() {}

func (w *Event_PayloadRequest) Unwrap() *PayloadRequest {
	return w.PayloadRequest
}

func (w *Event_PayloadRequest) Pb() applicationpb.Event_Type {
	if w == nil {
		return nil
	}
	if w.PayloadRequest == nil {
		return &applicationpb.Event_PayloadRequest{}
	}
	return &applicationpb.Event_PayloadRequest{PayloadRequest: (w.PayloadRequest).Pb()}
}

func (*Event_PayloadRequest) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*applicationpb.Event_PayloadRequest]()}
}

type Event_PayloadResponse struct {
	PayloadResponse *PayloadResponse
}

func (*Event_PayloadResponse) isEvent_Type() {}

func (w *Event_PayloadResponse) Unwrap() *PayloadResponse {
	return w.PayloadResponse
}

func (w *Event_PayloadResponse) Pb() applicationpb.Event_Type {
	if w == nil {
		return nil
	}
	if w.PayloadResponse == nil {
		return &applicationpb.Event_PayloadResponse{}
	}
	return &applicationpb.Event_PayloadResponse{PayloadResponse: (w.PayloadResponse).Pb()}
}

func (*Event_PayloadResponse) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*applicationpb.Event_PayloadResponse]()}
}

func EventFromPb(pb *applicationpb.Event) *Event {
	if pb == nil {
		return nil
	}
	return &Event{
		Type: Event_TypeFromPb(pb.Type),
	}
}

func (m *Event) Pb() *applicationpb.Event {
	if m == nil {
		return nil
	}
	pbMessage := &applicationpb.Event{}
	{
		if m.Type != nil {
			pbMessage.Type = (m.Type).Pb()
		}
	}

	return pbMessage
}

func (*Event) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*applicationpb.Event]()}
}

type NewHead struct {
	HeadId uint64
}

func NewHeadFromPb(pb *applicationpb.NewHead) *NewHead {
	if pb == nil {
		return nil
	}
	return &NewHead{
		HeadId: pb.HeadId,
	}
}

func (m *NewHead) Pb() *applicationpb.NewHead {
	if m == nil {
		return nil
	}
	pbMessage := &applicationpb.NewHead{}
	{
		pbMessage.HeadId = m.HeadId
	}

	return pbMessage
}

func (*NewHead) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*applicationpb.NewHead]()}
}

type PayloadRequest struct {
	HeadId uint64
}

func PayloadRequestFromPb(pb *applicationpb.PayloadRequest) *PayloadRequest {
	if pb == nil {
		return nil
	}
	return &PayloadRequest{
		HeadId: pb.HeadId,
	}
}

func (m *PayloadRequest) Pb() *applicationpb.PayloadRequest {
	if m == nil {
		return nil
	}
	pbMessage := &applicationpb.PayloadRequest{}
	{
		pbMessage.HeadId = m.HeadId
	}

	return pbMessage
}

func (*PayloadRequest) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*applicationpb.PayloadRequest]()}
}

type PayloadResponse struct {
	HeadId  uint64
	Payload *payloadpb.Payload
}

func PayloadResponseFromPb(pb *applicationpb.PayloadResponse) *PayloadResponse {
	if pb == nil {
		return nil
	}
	return &PayloadResponse{
		HeadId:  pb.HeadId,
		Payload: pb.Payload,
	}
}

func (m *PayloadResponse) Pb() *applicationpb.PayloadResponse {
	if m == nil {
		return nil
	}
	pbMessage := &applicationpb.PayloadResponse{}
	{
		pbMessage.HeadId = m.HeadId
		if m.Payload != nil {
			pbMessage.Payload = m.Payload
		}
	}

	return pbMessage
}

func (*PayloadResponse) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*applicationpb.PayloadResponse]()}
}
