// Code generated by Mir codegen. DO NOT EDIT.

package granitepb

import (
	reflect "reflect"
)

func (*Message) ReflectTypeOptions() []reflect.Type {
	return []reflect.Type{
		reflect.TypeOf((*Message_Decision)(nil)),
		reflect.TypeOf((*Message_ConsensusMsg)(nil)),
	}
}

func (*Event) ReflectTypeOptions() []reflect.Type {
	return []reflect.Type{
		reflect.TypeOf((*Event_ConvergeTimeout)(nil)),
	}
}
