// Code generated by Mir codegen. DO NOT EDIT.

package batchdbpbdsl

import (
	types1 "github.com/filecoin-project/mir/pkg/availability/multisigcollector/types"
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	events "github.com/filecoin-project/mir/pkg/pb/availabilitypb/batchdbpb/events"
	types2 "github.com/filecoin-project/mir/pkg/pb/availabilitypb/batchdbpb/types"
	types3 "github.com/filecoin-project/mir/pkg/pb/trantorpb/types"
	types4 "github.com/filecoin-project/mir/pkg/trantor/types"
	types "github.com/filecoin-project/mir/pkg/types"
)

// Module-specific dsl functions for emitting events.

func LookupBatch[C any](m dsl.Module, destModule types.ModuleID, batchId types1.BatchID, context *C) {
	contextID := m.DslHandle().StoreContext(context)

	origin := &types2.LookupBatchOrigin{
		Module: m.ModuleID(),
		Type:   &types2.LookupBatchOrigin_Dsl{Dsl: dsl.MirOrigin(contextID)},
	}

	dsl.EmitEvent(m, events.LookupBatch(destModule, batchId, origin))
}

func LookupBatchResponse(m dsl.Module, destModule types.ModuleID, found bool, txs []*types3.Transaction, origin *types2.LookupBatchOrigin) {
	dsl.EmitEvent(m, events.LookupBatchResponse(destModule, found, txs, origin))
}

func StoreBatch[C any](m dsl.Module, destModule types.ModuleID, batchId types1.BatchID, txs []*types3.Transaction, retentionIndex types4.RetentionIndex, context *C) {
	contextID := m.DslHandle().StoreContext(context)

	origin := &types2.StoreBatchOrigin{
		Module: m.ModuleID(),
		Type:   &types2.StoreBatchOrigin_Dsl{Dsl: dsl.MirOrigin(contextID)},
	}

	dsl.EmitEvent(m, events.StoreBatch(destModule, batchId, txs, retentionIndex, origin))
}

func BatchStored(m dsl.Module, destModule types.ModuleID, origin *types2.StoreBatchOrigin) {
	dsl.EmitEvent(m, events.BatchStored(destModule, origin))
}

func GarbageCollect(m dsl.Module, destModule types.ModuleID, retentionIndex types4.RetentionIndex) {
	dsl.EmitEvent(m, events.GarbageCollect(destModule, retentionIndex))
}
