// Code generated by Mir codegen. DO NOT EDIT.

package minerpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/minerpb/types"
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/payloadpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
)

// Module-specific dsl functions for processing events.

func UponEvent[W types.Event_TypeWrapper[Ev], Ev any](m dsl.Module, handler func(ev *Ev) error) {
	dsl.UponMirEvent[*types1.Event_Miner](m, func(ev *types.Event) error {
		w, ok := ev.Type.(W)
		if !ok {
			return nil
		}

		return handler(w.Unwrap())
	})
}

func UponBlockRequest(m dsl.Module, handler func(headId uint64, payload *types2.Payload) error) {
	UponEvent[*types.Event_BlockRequest](m, func(ev *types.BlockRequest) error {
		return handler(ev.HeadId, ev.Payload)
	})
}

func UponNewHead(m dsl.Module, handler func(headId uint64) error) {
	UponEvent[*types.Event_NewHead](m, func(ev *types.NewHead) error {
		return handler(ev.HeadId)
	})
}
