// Code generated by Mir codegen. DO NOT EDIT.

package accountabilitypbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	events "github.com/filecoin-project/mir/pkg/pb/accountabilitypb/events"
	types1 "github.com/filecoin-project/mir/pkg/pb/accountabilitypb/types"
	types "github.com/filecoin-project/mir/pkg/types"
)

// Module-specific dsl functions for emitting events.

func Predecided(m dsl.Module, destModule types.ModuleID, data []uint8) {
	dsl.EmitMirEvent(m, events.Predecided(destModule, data))
}

func Decided(m dsl.Module, destModule types.ModuleID, data []uint8) {
	dsl.EmitMirEvent(m, events.Decided(destModule, data))
}

func PoMs(m dsl.Module, destModule types.ModuleID, poms []*types1.PoM) {
	dsl.EmitMirEvent(m, events.PoMs(destModule, poms))
}
