// Code generated by Mir codegen. DO NOT EDIT.

package accountabilitypbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	types "github.com/filecoin-project/mir/pkg/pb/accountabilitypb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
)

// Module-specific dsl functions for processing events.

func UponEvent[W types.Event_TypeWrapper[Ev], Ev any](m dsl.Module, handler func(ev *Ev) error) {
	dsl.UponMirEvent[*types1.Event_Accountability](m, func(ev *types.Event) error {
		w, ok := ev.Type.(W)
		if !ok {
			return nil
		}

		return handler(w.Unwrap())
	})
}

func UponPoMs(m dsl.Module, handler func(poms []*types.PoM) error) {
	UponEvent[*types.Event_Poms](m, func(ev *types.PoMs) error {
		return handler(ev.Poms)
	})
}
