// Code generated by Mir codegen. DO NOT EDIT.

package statepbtypes

import (
	mirreflect "github.com/filecoin-project/mir/codegen/mirreflect"
	types "github.com/filecoin-project/mir/codegen/model/types"
	statepb "github.com/filecoin-project/mir/pkg/pb/blockchainpb/statepb"
	types1 "github.com/filecoin-project/mir/pkg/types"
	reflectutil "github.com/filecoin-project/mir/pkg/util/reflectutil"
)

type State struct {
	MessageHistory     []string
	LastSentTimestamps []*LastSentTimestamp
}

func StateFromPb(pb *statepb.State) *State {
	if pb == nil {
		return nil
	}
	return &State{
		MessageHistory: pb.MessageHistory,
		LastSentTimestamps: types.ConvertSlice(pb.LastSentTimestamps, func(t *statepb.LastSentTimestamp) *LastSentTimestamp {
			return LastSentTimestampFromPb(t)
		}),
	}
}

func (m *State) Pb() *statepb.State {
	if m == nil {
		return nil
	}
	pbMessage := &statepb.State{}
	{
		pbMessage.MessageHistory = m.MessageHistory
		pbMessage.LastSentTimestamps = types.ConvertSlice(m.LastSentTimestamps, func(t *LastSentTimestamp) *statepb.LastSentTimestamp {
			return (t).Pb()
		})
	}

	return pbMessage
}

func (*State) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*statepb.State]()}
}

type LastSentTimestamp struct {
	NodeId    types1.NodeID
	Timestamp int64
}

func LastSentTimestampFromPb(pb *statepb.LastSentTimestamp) *LastSentTimestamp {
	if pb == nil {
		return nil
	}
	return &LastSentTimestamp{
		NodeId:    (types1.NodeID)(pb.NodeId),
		Timestamp: pb.Timestamp,
	}
}

func (m *LastSentTimestamp) Pb() *statepb.LastSentTimestamp {
	if m == nil {
		return nil
	}
	pbMessage := &statepb.LastSentTimestamp{}
	{
		pbMessage.NodeId = (string)(m.NodeId)
		pbMessage.Timestamp = m.Timestamp
	}

	return pbMessage
}

func (*LastSentTimestamp) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*statepb.LastSentTimestamp]()}
}
