// Code generated by Mir codegen. DO NOT EDIT.

package tpmpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	events "github.com/filecoin-project/mir/pkg/pb/blockchainpb/tpmpb/events"
	types "github.com/filecoin-project/mir/pkg/types"
)

// Module-specific dsl functions for emitting events.

func NewHead(m dsl.Module, destModule types.ModuleID, headId uint64) {
	dsl.EmitMirEvent(m, events.NewHead(destModule, headId))
}
