// Code generated by Mir codegen. DO NOT EDIT.

package tpmpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/tpmpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
)

// Module-specific dsl functions for processing events.

func UponEvent[W types.Event_TypeWrapper[Ev], Ev any](m dsl.Module, handler func(ev *Ev) error) {
	dsl.UponMirEvent[*types1.Event_Tpm](m, func(ev *types.Event) error {
		w, ok := ev.Type.(W)
		if !ok {
			return nil
		}

		return handler(w.Unwrap())
	})
}

func UponNewBlockRequest(m dsl.Module, handler func(headId uint64) error) {
	UponEvent[*types.Event_NewBlockRequest](m, func(ev *types.NewBlockRequest) error {
		return handler(ev.HeadId)
	})
}
