// Code generated by Mir codegen. DO NOT EDIT.

package interceptorpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	types "github.com/filecoin-project/mir/pkg/pb/blockchainpb/interceptorpb/types"
	types3 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/statepb/types"
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
)

// Module-specific dsl functions for processing events.

func UponEvent[W types.Event_TypeWrapper[Ev], Ev any](m dsl.Module, handler func(ev *Ev) error) {
	dsl.UponMirEvent[*types1.Event_Bcinterceptor](m, func(ev *types.Event) error {
		w, ok := ev.Type.(W)
		if !ok {
			return nil
		}

		return handler(w.Unwrap())
	})
}

func UponTreeUpdate(m dsl.Module, handler func(tree *types2.Blocktree, headId uint64) error) {
	UponEvent[*types.Event_TreeUpdate](m, func(ev *types.TreeUpdate) error {
		return handler(ev.Tree, ev.HeadId)
	})
}

func UponNewOrphan(m dsl.Module, handler func(orphan *types2.Block) error) {
	UponEvent[*types.Event_NewOrphan](m, func(ev *types.NewOrphan) error {
		return handler(ev.Orphan)
	})
}

func UponAppUpdate(m dsl.Module, handler func(state *types3.State) error) {
	UponEvent[*types.Event_AppUpdate](m, func(ev *types.AppUpdate) error {
		return handler(ev.State)
	})
}
