// Code generated by Mir codegen. DO NOT EDIT.

package trantorpbevents

import (
	types3 "github.com/filecoin-project/mir/pkg/pb/batchfetcherpb/types"
	types4 "github.com/filecoin-project/mir/pkg/pb/checkpointpb/types"
	types2 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/trantorpb/types"
	types "github.com/filecoin-project/mir/pkg/trantor/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

func ClientProgress(destModule stdtypes.ModuleID, progress map[types.ClientID]*types1.DeliveredTXs) *types2.Event {
	return &types2.Event{
		DestModule: destModule,
		Type: &types2.Event_BatchFetcher{
			BatchFetcher: &types3.Event{
				Type: &types3.Event_ClientProgress{
					ClientProgress: &types1.ClientProgress{
						Progress: progress,
					},
				},
			},
		},
	}
}

func EpochConfig(destModule stdtypes.ModuleID, epochNr types.EpochNr, firstSn types.SeqNr, length uint64, memberships []*types1.Membership) *types2.Event {
	return &types2.Event{
		DestModule: destModule,
		Type: &types2.Event_Checkpoint{
			Checkpoint: &types4.Event{
				Type: &types4.Event_EpochConfig{
					EpochConfig: &types1.EpochConfig{
						EpochNr:     epochNr,
						FirstSn:     firstSn,
						Length:      length,
						Memberships: memberships,
					},
				},
			},
		},
	}
}
