// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: blockchainpb/bcmpb/bcmpb.proto

package bcmpb

import (
	blockchainpb "github.com/filecoin-project/mir/pkg/pb/blockchainpb"
	_ "github.com/filecoin-project/mir/pkg/pb/mir"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*Event_NewBlock
	Type isEvent_Type `protobuf_oneof:"type"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchainpb_bcmpb_bcmpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_blockchainpb_bcmpb_bcmpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_blockchainpb_bcmpb_bcmpb_proto_rawDescGZIP(), []int{0}
}

func (m *Event) GetType() isEvent_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Event) GetNewBlock() *NewBlock {
	if x, ok := x.GetType().(*Event_NewBlock); ok {
		return x.NewBlock
	}
	return nil
}

type isEvent_Type interface {
	isEvent_Type()
}

type Event_NewBlock struct {
	NewBlock *NewBlock `protobuf:"bytes,1,opt,name=new_block,json=newBlock,proto3,oneof"`
}

func (*Event_NewBlock) isEvent_Type() {}

type NewBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *blockchainpb.Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *NewBlock) Reset() {
	*x = NewBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchainpb_bcmpb_bcmpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBlock) ProtoMessage() {}

func (x *NewBlock) ProtoReflect() protoreflect.Message {
	mi := &file_blockchainpb_bcmpb_bcmpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBlock.ProtoReflect.Descriptor instead.
func (*NewBlock) Descriptor() ([]byte, []int) {
	return file_blockchainpb_bcmpb_bcmpb_proto_rawDescGZIP(), []int{1}
}

func (x *NewBlock) GetBlock() *blockchainpb.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_blockchainpb_bcmpb_bcmpb_proto protoreflect.FileDescriptor

var file_blockchainpb_bcmpb_bcmpb_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x70, 0x62, 0x2f, 0x62,
	0x63, 0x6d, 0x70, 0x62, 0x2f, 0x62, 0x63, 0x6d, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x62, 0x63, 0x6d, 0x70, 0x62, 0x1a, 0x1f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x70, 0x62, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x6d, 0x69, 0x72, 0x2f, 0x63, 0x6f,
	0x64, 0x65, 0x67, 0x65, 0x6e, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x2e, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x63, 0x6d, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x77, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x3a,
	0x04, 0x90, 0xa6, 0x1d, 0x01, 0x42, 0x0c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x04, 0x80,
	0xa6, 0x1d, 0x01, 0x22, 0x3b, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x29, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x70, 0x62, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x3a, 0x04, 0x98, 0xa6, 0x1d, 0x01,
	0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x69, 0x6c, 0x65, 0x63, 0x6f, 0x69, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f,
	0x6d, 0x69, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x70, 0x62, 0x2f, 0x62, 0x63, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blockchainpb_bcmpb_bcmpb_proto_rawDescOnce sync.Once
	file_blockchainpb_bcmpb_bcmpb_proto_rawDescData = file_blockchainpb_bcmpb_bcmpb_proto_rawDesc
)

func file_blockchainpb_bcmpb_bcmpb_proto_rawDescGZIP() []byte {
	file_blockchainpb_bcmpb_bcmpb_proto_rawDescOnce.Do(func() {
		file_blockchainpb_bcmpb_bcmpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchainpb_bcmpb_bcmpb_proto_rawDescData)
	})
	return file_blockchainpb_bcmpb_bcmpb_proto_rawDescData
}

var file_blockchainpb_bcmpb_bcmpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blockchainpb_bcmpb_bcmpb_proto_goTypes = []interface{}{
	(*Event)(nil),              // 0: bcmpb.Event
	(*NewBlock)(nil),           // 1: bcmpb.NewBlock
	(*blockchainpb.Block)(nil), // 2: blockchainpb.Block
}
var file_blockchainpb_bcmpb_bcmpb_proto_depIdxs = []int32{
	1, // 0: bcmpb.Event.new_block:type_name -> bcmpb.NewBlock
	2, // 1: bcmpb.NewBlock.block:type_name -> blockchainpb.Block
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blockchainpb_bcmpb_bcmpb_proto_init() }
func file_blockchainpb_bcmpb_bcmpb_proto_init() {
	if File_blockchainpb_bcmpb_bcmpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blockchainpb_bcmpb_bcmpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchainpb_bcmpb_bcmpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_blockchainpb_bcmpb_bcmpb_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Event_NewBlock)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchainpb_bcmpb_bcmpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchainpb_bcmpb_bcmpb_proto_goTypes,
		DependencyIndexes: file_blockchainpb_bcmpb_bcmpb_proto_depIdxs,
		MessageInfos:      file_blockchainpb_bcmpb_bcmpb_proto_msgTypes,
	}.Build()
	File_blockchainpb_bcmpb_bcmpb_proto = out.File
	file_blockchainpb_bcmpb_bcmpb_proto_rawDesc = nil
	file_blockchainpb_bcmpb_bcmpb_proto_goTypes = nil
	file_blockchainpb_bcmpb_bcmpb_proto_depIdxs = nil
}
