// Code generated by Mir codegen. DO NOT EDIT.

package hasherpbevents

import (
	types1 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
	types "github.com/filecoin-project/mir/pkg/pb/hasherpb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

func Request(destModule stdtypes.ModuleID, data []*types.HashData, origin *types.HashOrigin) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Hasher{
			Hasher: &types.Event{
				Type: &types.Event_Request{
					Request: &types.Request{
						Data:   data,
						Origin: origin,
					},
				},
			},
		},
	}
}

func Result(destModule stdtypes.ModuleID, digests [][]uint8, origin *types.HashOrigin) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Hasher{
			Hasher: &types.Event{
				Type: &types.Event_Result{
					Result: &types.Result{
						Digests: digests,
						Origin:  origin,
					},
				},
			},
		},
	}
}

func RequestOne(destModule stdtypes.ModuleID, data *types.HashData, origin *types.HashOrigin) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Hasher{
			Hasher: &types.Event{
				Type: &types.Event_RequestOne{
					RequestOne: &types.RequestOne{
						Data:   data,
						Origin: origin,
					},
				},
			},
		},
	}
}

func ResultOne(destModule stdtypes.ModuleID, digest []uint8, origin *types.HashOrigin) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Hasher{
			Hasher: &types.Event{
				Type: &types.Event_ResultOne{
					ResultOne: &types.ResultOne{
						Digest: digest,
						Origin: origin,
					},
				},
			},
		},
	}
}
