// Code generated by Mir codegen. DO NOT EDIT.

package eventpbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	events "github.com/filecoin-project/mir/pkg/pb/eventpb/events"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

// Module-specific dsl functions for emitting events.

func Init(m dsl.Module, destModule stdtypes.ModuleID) {
	dsl.EmitMirEvent(m, events.Init(destModule))
}
