// Code generated by Mir codegen. DO NOT EDIT.

package checkpointvaliditycheckerpbtypes

import (
	mirreflect "github.com/filecoin-project/mir/codegen/mirreflect"
	types3 "github.com/filecoin-project/mir/codegen/model/types"
	checkpointvaliditycheckerpb "github.com/filecoin-project/mir/pkg/pb/checkpointpb/checkpointvaliditycheckerpb"
	types "github.com/filecoin-project/mir/pkg/pb/checkpointpb/types"
	types5 "github.com/filecoin-project/mir/pkg/pb/contextstorepb/types"
	types6 "github.com/filecoin-project/mir/pkg/pb/dslpb/types"
	trantorpb "github.com/filecoin-project/mir/pkg/pb/trantorpb"
	types2 "github.com/filecoin-project/mir/pkg/pb/trantorpb/types"
	types1 "github.com/filecoin-project/mir/pkg/trantor/types"
	types4 "github.com/filecoin-project/mir/pkg/types"
	reflectutil "github.com/filecoin-project/mir/pkg/util/reflectutil"
)

type Event struct {
	Type Event_Type
}

type Event_Type interface {
	mirreflect.GeneratedType
	isEvent_Type()
	Pb() checkpointvaliditycheckerpb.Event_Type
}

type Event_TypeWrapper[T any] interface {
	Event_Type
	Unwrap() *T
}

func Event_TypeFromPb(pb checkpointvaliditycheckerpb.Event_Type) Event_Type {
	if pb == nil {
		return nil
	}
	switch pb := pb.(type) {
	case *checkpointvaliditycheckerpb.Event_ValidateCheckpoint:
		return &Event_ValidateCheckpoint{ValidateCheckpoint: ValidateCheckpointFromPb(pb.ValidateCheckpoint)}
	case *checkpointvaliditycheckerpb.Event_CheckpointValidated:
		return &Event_CheckpointValidated{CheckpointValidated: CheckpointValidatedFromPb(pb.CheckpointValidated)}
	}
	return nil
}

type Event_ValidateCheckpoint struct {
	ValidateCheckpoint *ValidateCheckpoint
}

func (*Event_ValidateCheckpoint) isEvent_Type() {}

func (w *Event_ValidateCheckpoint) Unwrap() *ValidateCheckpoint {
	return w.ValidateCheckpoint
}

func (w *Event_ValidateCheckpoint) Pb() checkpointvaliditycheckerpb.Event_Type {
	if w == nil {
		return nil
	}
	if w.ValidateCheckpoint == nil {
		return &checkpointvaliditycheckerpb.Event_ValidateCheckpoint{}
	}
	return &checkpointvaliditycheckerpb.Event_ValidateCheckpoint{ValidateCheckpoint: (w.ValidateCheckpoint).Pb()}
}

func (*Event_ValidateCheckpoint) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*checkpointvaliditycheckerpb.Event_ValidateCheckpoint]()}
}

type Event_CheckpointValidated struct {
	CheckpointValidated *CheckpointValidated
}

func (*Event_CheckpointValidated) isEvent_Type() {}

func (w *Event_CheckpointValidated) Unwrap() *CheckpointValidated {
	return w.CheckpointValidated
}

func (w *Event_CheckpointValidated) Pb() checkpointvaliditycheckerpb.Event_Type {
	if w == nil {
		return nil
	}
	if w.CheckpointValidated == nil {
		return &checkpointvaliditycheckerpb.Event_CheckpointValidated{}
	}
	return &checkpointvaliditycheckerpb.Event_CheckpointValidated{CheckpointValidated: (w.CheckpointValidated).Pb()}
}

func (*Event_CheckpointValidated) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*checkpointvaliditycheckerpb.Event_CheckpointValidated]()}
}

func EventFromPb(pb *checkpointvaliditycheckerpb.Event) *Event {
	if pb == nil {
		return nil
	}
	return &Event{
		Type: Event_TypeFromPb(pb.Type),
	}
}

func (m *Event) Pb() *checkpointvaliditycheckerpb.Event {
	if m == nil {
		return nil
	}
	pbMessage := &checkpointvaliditycheckerpb.Event{}
	{
		if m.Type != nil {
			pbMessage.Type = (m.Type).Pb()
		}
	}

	return pbMessage
}

func (*Event) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*checkpointvaliditycheckerpb.Event]()}
}

type ValidateCheckpoint struct {
	Checkpoint  *types.StableCheckpoint
	EpochNr     types1.EpochNr
	Memberships []*types2.Membership
	Origin      *ValidateChkpOrigin
}

func ValidateCheckpointFromPb(pb *checkpointvaliditycheckerpb.ValidateCheckpoint) *ValidateCheckpoint {
	if pb == nil {
		return nil
	}
	return &ValidateCheckpoint{
		Checkpoint: types.StableCheckpointFromPb(pb.Checkpoint),
		EpochNr:    (types1.EpochNr)(pb.EpochNr),
		Memberships: types3.ConvertSlice(pb.Memberships, func(t *trantorpb.Membership) *types2.Membership {
			return types2.MembershipFromPb(t)
		}),
		Origin: ValidateChkpOriginFromPb(pb.Origin),
	}
}

func (m *ValidateCheckpoint) Pb() *checkpointvaliditycheckerpb.ValidateCheckpoint {
	if m == nil {
		return nil
	}
	pbMessage := &checkpointvaliditycheckerpb.ValidateCheckpoint{}
	{
		if m.Checkpoint != nil {
			pbMessage.Checkpoint = (m.Checkpoint).Pb()
		}
		pbMessage.EpochNr = (uint64)(m.EpochNr)
		pbMessage.Memberships = types3.ConvertSlice(m.Memberships, func(t *types2.Membership) *trantorpb.Membership {
			return (t).Pb()
		})
		if m.Origin != nil {
			pbMessage.Origin = (m.Origin).Pb()
		}
	}

	return pbMessage
}

func (*ValidateCheckpoint) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*checkpointvaliditycheckerpb.ValidateCheckpoint]()}
}

type CheckpointValidated struct {
	Error  error
	Origin *ValidateChkpOrigin
}

func CheckpointValidatedFromPb(pb *checkpointvaliditycheckerpb.CheckpointValidated) *CheckpointValidated {
	if pb == nil {
		return nil
	}
	return &CheckpointValidated{
		Error:  types3.StringToError(pb.Error),
		Origin: ValidateChkpOriginFromPb(pb.Origin),
	}
}

func (m *CheckpointValidated) Pb() *checkpointvaliditycheckerpb.CheckpointValidated {
	if m == nil {
		return nil
	}
	pbMessage := &checkpointvaliditycheckerpb.CheckpointValidated{}
	{
		pbMessage.Error = types3.ErrorToString(m.Error)
		if m.Origin != nil {
			pbMessage.Origin = (m.Origin).Pb()
		}
	}

	return pbMessage
}

func (*CheckpointValidated) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*checkpointvaliditycheckerpb.CheckpointValidated]()}
}

type ValidateChkpOrigin struct {
	Module types4.ModuleID
	Type   ValidateChkpOrigin_Type
}

type ValidateChkpOrigin_Type interface {
	mirreflect.GeneratedType
	isValidateChkpOrigin_Type()
	Pb() checkpointvaliditycheckerpb.ValidateChkpOrigin_Type
}

type ValidateChkpOrigin_TypeWrapper[T any] interface {
	ValidateChkpOrigin_Type
	Unwrap() *T
}

func ValidateChkpOrigin_TypeFromPb(pb checkpointvaliditycheckerpb.ValidateChkpOrigin_Type) ValidateChkpOrigin_Type {
	if pb == nil {
		return nil
	}
	switch pb := pb.(type) {
	case *checkpointvaliditycheckerpb.ValidateChkpOrigin_ContextStore:
		return &ValidateChkpOrigin_ContextStore{ContextStore: types5.OriginFromPb(pb.ContextStore)}
	case *checkpointvaliditycheckerpb.ValidateChkpOrigin_Dsl:
		return &ValidateChkpOrigin_Dsl{Dsl: types6.OriginFromPb(pb.Dsl)}
	}
	return nil
}

type ValidateChkpOrigin_ContextStore struct {
	ContextStore *types5.Origin
}

func (*ValidateChkpOrigin_ContextStore) isValidateChkpOrigin_Type() {}

func (w *ValidateChkpOrigin_ContextStore) Unwrap() *types5.Origin {
	return w.ContextStore
}

func (w *ValidateChkpOrigin_ContextStore) Pb() checkpointvaliditycheckerpb.ValidateChkpOrigin_Type {
	if w == nil {
		return nil
	}
	if w.ContextStore == nil {
		return &checkpointvaliditycheckerpb.ValidateChkpOrigin_ContextStore{}
	}
	return &checkpointvaliditycheckerpb.ValidateChkpOrigin_ContextStore{ContextStore: (w.ContextStore).Pb()}
}

func (*ValidateChkpOrigin_ContextStore) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*checkpointvaliditycheckerpb.ValidateChkpOrigin_ContextStore]()}
}

type ValidateChkpOrigin_Dsl struct {
	Dsl *types6.Origin
}

func (*ValidateChkpOrigin_Dsl) isValidateChkpOrigin_Type() {}

func (w *ValidateChkpOrigin_Dsl) Unwrap() *types6.Origin {
	return w.Dsl
}

func (w *ValidateChkpOrigin_Dsl) Pb() checkpointvaliditycheckerpb.ValidateChkpOrigin_Type {
	if w == nil {
		return nil
	}
	if w.Dsl == nil {
		return &checkpointvaliditycheckerpb.ValidateChkpOrigin_Dsl{}
	}
	return &checkpointvaliditycheckerpb.ValidateChkpOrigin_Dsl{Dsl: (w.Dsl).Pb()}
}

func (*ValidateChkpOrigin_Dsl) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*checkpointvaliditycheckerpb.ValidateChkpOrigin_Dsl]()}
}

func ValidateChkpOriginFromPb(pb *checkpointvaliditycheckerpb.ValidateChkpOrigin) *ValidateChkpOrigin {
	if pb == nil {
		return nil
	}
	return &ValidateChkpOrigin{
		Module: (types4.ModuleID)(pb.Module),
		Type:   ValidateChkpOrigin_TypeFromPb(pb.Type),
	}
}

func (m *ValidateChkpOrigin) Pb() *checkpointvaliditycheckerpb.ValidateChkpOrigin {
	if m == nil {
		return nil
	}
	pbMessage := &checkpointvaliditycheckerpb.ValidateChkpOrigin{}
	{
		pbMessage.Module = (string)(m.Module)
		if m.Type != nil {
			pbMessage.Type = (m.Type).Pb()
		}
	}

	return pbMessage
}

func (*ValidateChkpOrigin) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*checkpointvaliditycheckerpb.ValidateChkpOrigin]()}
}
