// Code generated by Mir codegen. DO NOT EDIT.

package accountabilitypbevents

import (
	types1 "github.com/filecoin-project/mir/pkg/pb/accountabilitypb/types"
	types2 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
	types "github.com/filecoin-project/mir/pkg/types"
)

func PoMs(destModule types.ModuleID, poms []*types1.PoM) *types2.Event {
	return &types2.Event{
		DestModule: destModule,
		Type: &types2.Event_Accountability{
			Accountability: &types1.Event{
				Type: &types1.Event_Poms{
					Poms: &types1.PoMs{
						Poms: poms,
					},
				},
			},
		},
	}
}
