// Code generated by Mir codegen. DO NOT EDIT.

package synchronizerpbmsgs

import (
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/synchronizerpb/types"
	types3 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/messagepb/types"
	types "github.com/filecoin-project/mir/pkg/types"
)

func ChainRequest(destModule types.ModuleID, requestId string, blockId uint64, leaveIds []uint64) *types1.Message {
	return &types1.Message{
		DestModule: destModule,
		Type: &types1.Message_Synchronizer{
			Synchronizer: &types2.Message{
				Type: &types2.Message_ChainRequest{
					ChainRequest: &types2.ChainRequest{
						RequestId: requestId,
						BlockId:   blockId,
						LeaveIds:  leaveIds,
					},
				},
			},
		},
	}
}

func ChainResponse(destModule types.ModuleID, requestId string, found bool, chain []*types3.Block) *types1.Message {
	return &types1.Message{
		DestModule: destModule,
		Type: &types1.Message_Synchronizer{
			Synchronizer: &types2.Message{
				Type: &types2.Message_ChainResponse{
					ChainResponse: &types2.ChainResponse{
						RequestId: requestId,
						Found:     found,
						Chain:     chain,
					},
				},
			},
		},
	}
}
