// Code generated by Mir codegen. DO NOT EDIT.

package minerpbevents

import (
	blockchainpb "github.com/filecoin-project/mir/pkg/pb/blockchainpb"
	types2 "github.com/filecoin-project/mir/pkg/pb/blockchainpb/minerpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
	types "github.com/filecoin-project/mir/pkg/types"
)

func BlockRequest(destModule types.ModuleID, headId uint64, payload *blockchainpb.Payload) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_Miner{
			Miner: &types2.Event{
				Type: &types2.Event_BlockRequest{
					BlockRequest: &types2.BlockRequest{
						HeadId:  headId,
						Payload: payload,
					},
				},
			},
		},
	}
}
