// Code generated by Mir codegen. DO NOT EDIT.

package tpmpbtypes

import (
	mirreflect "github.com/filecoin-project/mir/codegen/mirreflect"
	tpmpb "github.com/filecoin-project/mir/pkg/pb/blockchainpb/tpmpb"
	reflectutil "github.com/filecoin-project/mir/pkg/util/reflectutil"
)

type Event struct {
	Type Event_Type
}

type Event_Type interface {
	mirreflect.GeneratedType
	isEvent_Type()
	Pb() tpmpb.Event_Type
}

type Event_TypeWrapper[T any] interface {
	Event_Type
	Unwrap() *T
}

func Event_TypeFromPb(pb tpmpb.Event_Type) Event_Type {
	if pb == nil {
		return nil
	}
	switch pb := pb.(type) {
	case *tpmpb.Event_NewBlockRequest:
		return &Event_NewBlockRequest{NewBlockRequest: NewBlockRequestFromPb(pb.NewBlockRequest)}
	}
	return nil
}

type Event_NewBlockRequest struct {
	NewBlockRequest *NewBlockRequest
}

func (*Event_NewBlockRequest) isEvent_Type() {}

func (w *Event_NewBlockRequest) Unwrap() *NewBlockRequest {
	return w.NewBlockRequest
}

func (w *Event_NewBlockRequest) Pb() tpmpb.Event_Type {
	if w == nil {
		return nil
	}
	if w.NewBlockRequest == nil {
		return &tpmpb.Event_NewBlockRequest{}
	}
	return &tpmpb.Event_NewBlockRequest{NewBlockRequest: (w.NewBlockRequest).Pb()}
}

func (*Event_NewBlockRequest) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*tpmpb.Event_NewBlockRequest]()}
}

func EventFromPb(pb *tpmpb.Event) *Event {
	if pb == nil {
		return nil
	}
	return &Event{
		Type: Event_TypeFromPb(pb.Type),
	}
}

func (m *Event) Pb() *tpmpb.Event {
	if m == nil {
		return nil
	}
	pbMessage := &tpmpb.Event{}
	{
		if m.Type != nil {
			pbMessage.Type = (m.Type).Pb()
		}
	}

	return pbMessage
}

func (*Event) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*tpmpb.Event]()}
}

type NewBlockRequest struct {
	HeadId uint64
}

func NewBlockRequestFromPb(pb *tpmpb.NewBlockRequest) *NewBlockRequest {
	if pb == nil {
		return nil
	}
	return &NewBlockRequest{
		HeadId: pb.HeadId,
	}
}

func (m *NewBlockRequest) Pb() *tpmpb.NewBlockRequest {
	if m == nil {
		return nil
	}
	pbMessage := &tpmpb.NewBlockRequest{}
	{
		pbMessage.HeadId = m.HeadId
	}

	return pbMessage
}

func (*NewBlockRequest) MirReflect() mirreflect.Type {
	return mirreflect.TypeImpl{PbType_: reflectutil.TypeOf[*tpmpb.NewBlockRequest]()}
}
