// Code generated by Mir codegen. DO NOT EDIT.

package synchronizerpb

type Event_Type = isEvent_Type

type Event_TypeWrapper[T any] interface {
	Event_Type
	Unwrap() *T
}

func (w *Event_SyncRequest) Unwrap() *SyncRequest {
	return w.SyncRequest
}

type Message_Type = isMessage_Type

type Message_TypeWrapper[T any] interface {
	Message_Type
	Unwrap() *T
}

func (w *Message_ChainRequest) Unwrap() *ChainRequest {
	return w.ChainRequest
}

func (w *Message_ChainResponse) Unwrap() *ChainResponse {
	return w.ChainResponse
}
