// Code generated by Mir codegen. DO NOT EDIT.

package pprepvalidatorpbevents

import (
	types2 "github.com/filecoin-project/mir/pkg/pb/eventpb/types"
	types1 "github.com/filecoin-project/mir/pkg/pb/ordererpb/pprepvalidatorpb/types"
	types "github.com/filecoin-project/mir/pkg/pb/pbftpb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

func ValidatePreprepare(destModule stdtypes.ModuleID, preprepare *types.Preprepare, origin *types1.ValidatePreprepareOrigin) *types2.Event {
	return &types2.Event{
		DestModule: destModule,
		Type: &types2.Event_PprepValiadtor{
			PprepValiadtor: &types1.Event{
				Type: &types1.Event_ValidatePreprepare{
					ValidatePreprepare: &types1.ValidatePreprepare{
						Preprepare: preprepare,
						Origin:     origin,
					},
				},
			},
		},
	}
}

func PreprepareValidated(destModule stdtypes.ModuleID, error error, origin *types1.ValidatePreprepareOrigin) *types2.Event {
	return &types2.Event{
		DestModule: destModule,
		Type: &types2.Event_PprepValiadtor{
			PprepValiadtor: &types1.Event{
				Type: &types1.Event_PreprepareValidated{
					PreprepareValidated: &types1.PreprepareValidated{
						Error:  error,
						Origin: origin,
					},
				},
			},
		},
	}
}
