---
- name: Run Mir benchmark nodes
  hosts: all
  become: False
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/mir/bin:"
  tasks:
    - name: "Create membership file"
      ansible.builtin.script:
        cmd: scripts/create-membership.sh '{{ ansible_play_hosts_all }}'
    - name: "Run benchmark node"
      ansible.builtin.script:
        cmd: scripts/run-bench-node.sh "{{ lookup('ansible.utils.index_of', ansible_play_hosts_all, 'eq', ansible_host) }}"
...