---
- name: Initialize Mir benchmark VM
  hosts: all
  gather_facts: False
  become: False
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/go/bin"
  tasks:
    - name: "Install Go"
      become: True
      community.general.snap:
        name:
          - go
        classic: True
        channel: 1.18/stable
        state: present
    - name: "Install snaps"
      become: True
      community.general.snap:
        name:
          - tmux
          - protobuf
        classic: True
        state: present
    - name: "Install apt packages"
      become: True
      ansible.builtin.apt:
        name:
          - make
          - python3
        state: present
    - name: Clone Mir repo from GitHub
      ansible.builtin.git:
        repo: https://github.com/matejpavlovic/mir.git
        dest: ~/mir
    - name: "Check out the selected code version: {{ git_version }}"
      ansible.builtin.git:
        repo: https://github.com/matejpavlovic/mir.git
        dest: ~/mir
        single_branch: True
        version: "{{ git_version }}"
        force: True
    - name: compile Mir benchmark
      make:
        chdir: ~/mir
        target: bin/bench
    - name: compile Chat demo
      make:
        chdir: ~/mir
        target: bin/chat-demo
    - name: "Run setup script"
      ansible.builtin.script:
        # Single quotes are important here (https://github.com/ansible/ansible/issues/44897)
        cmd: scripts/setup.sh
...
