---
- name: Run Mir benchmark nodes
  hosts: all
  gather_facts: False
  become: False
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/mir/bin:"
  tasks:
    - name: Create membership file
      ansible.builtin.script:
        cmd: scripts/create-membership.sh '{{ ansible_play_hosts_all }}'
    - name: Run benchmark node
      ansible.builtin.script:
        cmd: scripts/start-benchmark.sh "{{ lookup('ansible.utils.index_of', ansible_play_hosts_all, 'eq', ansible_host) }}"
- name: Fetch membership file
  hosts: all[0]
  gather_facts: False
  become: False
  tasks:
    - name: Fetch membership file
      ansible.builtin.fetch:
        flat: True
        src: membership
        dest: membership
...