// Code generated by Mir codegen. DO NOT EDIT.

package isspbdsl

import (
	dsl "github.com/filecoin-project/mir/pkg/dsl"
	types "github.com/filecoin-project/mir/pkg/pb/isspb/types"
	dsl1 "github.com/filecoin-project/mir/pkg/pb/messagepb/dsl"
	types1 "github.com/filecoin-project/mir/pkg/pb/messagepb/types"
	stdtypes "github.com/filecoin-project/mir/stdtypes"
)

// Module-specific dsl functions for processing net messages.

func UponISSMessageReceived[W types.ISSMessage_TypeWrapper[M], M any](m dsl.Module, handler func(from stdtypes.NodeID, msg *M) error) {
	dsl1.UponMessageReceived[*types1.Message_Iss](m, func(from stdtypes.NodeID, msg *types.ISSMessage) error {
		w, ok := msg.Type.(W)
		if !ok {
			return nil
		}

		return handler(from, w.Unwrap())
	})
}
